name: 'Go Actions Cache'
description: 'A GitHub Action to use a custom GOCACHEPROG'
inputs:
  version:
    description: 'The version of the Go Actions Cache to use'
    default: '0.0.1'
  prefix:
    description: A prefix to add to cache keys to more easily identify them
    default: 'actions-cache-go-'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: inputs.version == '0'
    - shell: bash
      name: Download Go Actions Cache
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        if command -v actions-cache-go &> /dev/null; then
          echo "actions-cache-go already installed"
          exit 0
        fi

        dir="$(mktemp -d)"

        if [ "${{inputs.version }}" = "0" ]; then
          docker buildx build --output="${dir}" .
        else
          gh release download v${{ inputs.version }} --repo ${{ github.repository }} --pattern "go-actions-cache-$(uname -m).tar.gz"
          tar -xvf go-actions-cache-$(uname -m).tar.gz
          mv go-actions-cache "${dir}/actions-cache-go"
        fi

        echo "PATH=${dir}:$PATH" >> $GITHUB_ENV
    - shell: bash
      name: 'Set Go Actions Cache Environment Variables'
      run: |
        echo "GOCACHEPROG=actions-cache-go" >> $GITHUB_ENV
        if [ -z "${GOEXPERIMENT}" ]; then
          echo "GOEXPERIMENT=cacheprog" >> $GITHUB_ENV
        else
          echo "GOEXPERIMENT=cacheprog,${GOEXPERIMENT}" >> $GITHUB_ENV
        fi
        echo "GOEXPERIMENT=cacheprog,${GOEXPERIMENT}" >> $GITHUB_ENV

        if [ -n "${{ inputs.prefix }}" ]; then
          echo "ACTIONS_CACHE_GO_PREFIX=${{ inputs.prefix }}" >> $GITHUB_ENV
        fi
    - uses: crazy-max/ghaction-github-runtime@v3
      name: Expose github actions info for go-actions-cache