name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24]
        version: ["0.0.1", "0", ""]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Use Go Actions Cache
        if: matrix.version != ''
        uses: ./.github/actions/go-actions-cache
        with:
          version: '${{ matrix.version }}'
          debug: true
      - name: Build project (first time)
        run: go build ./...
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build project (second time)
        run: go build ./...
        env:
          GITHUB_TOKEN: ${{ github.token }}